### ISSUE TITLE
unconnected layers in a DSLTrans transformation make the MPS IDE block

### ISSUE THREAD

**Issue by levilucio** [mbeddr/language_verification#20]
- Build a first layer in a DSLTrans transformation with some rule inside
- Build a second layer (can be empty), but don't connect it to the first
- Some error should be thrown, and/or a constraint should be put on the language such that such models are not possible. The constraint cannot only be put on the metamodel (1 cardinality for the previous layer) as the first layer never has a predecessor
- Right now the MPS IDE freezes

**Comment by BentleyJOakes** [comment]
As well, a layer should only be the previous source for at most one other layer.
For example, layers B and C cannot both follow A

**Comment by BentleyJOakes** [comment]
Fixed in commit ad9fee540b491cd3d917b5ede7605986596ca4a0

Added constraints to layer connections. Only one layer can have no prevSource. No two layers can have the same prev source. All prev sources must be to the previous layers in the transformation.

Note that this last restriction means that you cannot arbitrarily rearrange the layers in the transformation. If this is not desired, it can be changed under DSLTrans/Constraints/PreviousLayer_Constraints.
